function [] = write_log_data(dataFile, data)

fprintf('run:%d\t supRun:%d\t subRun:%d\t trial:%3d\t onset:%3.4f\t plan:%3.4f\t pulse:%d\t supCate:%d\t subCate:%d\t imgID:%2d\t resp:%d\t Corr:%d\t RT:%3.4f\n', ...
    data.run, ...
    data.supRun, ...
    data.subRun, ...
    data.trial, ...
    data.onset, ...
    data.planned, ...
    data.pulse, ...
    data.supCate, ...
    data.subCate, ...
    data.img, ...
    data.response, ...
    data.correct, ...
    data.rt);

fprintf(dataFile, '%d\t %d\t %d\t %3d\t %3.4f\t %3.4f\t %d\t %d\t %d\t %2d\t %d\t %d\t %3.4f\n', ...
    data.run, ...
    data.supRun, ...
    data.subRun, ...
    data.trial, ...
    data.onset, ...
    data.planned, ...
    data.pulse, ...
    data.supCate, ...
    data.subCate, ...
    data.img, ...
    data.response, ...
    data.correct, ...
    data.rt);